name: Build and Test Insurance App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        
    - name: Verify imports
      run: |
        cd src
        python -c "from app import InsuranceApp; import pandas as pd; print('Все импорты работают')"
        
    - name: Run headless test
      run: |
        cd src
        python -c "
import sys
import os
os.environ['DISPLAY'] = ':99.0'  # Для headless режима

# Проверка основных функций без создания GUI
from app import InsuranceApp, REGEX, clean_text

# Тест функции clean_text
assert clean_text('Тест,01-01-01,текст') == 'Тест текст'
assert clean_text('Иванов Иван Иванович текст') == 'текст'

# Тест регулярного выражения
assert REGEX.search('гражданской ответственности') is not None
assert REGEX.search('страхование гражданской ответсвенности') is not None
assert REGEX.search('обычный текст') is None

print('Все тесты пройдены успешно!')
sys.exit(0)
"
