name: Build and Test Insurance App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Wine and Xvfb
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine wine32 xvfb
        wine --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pyinstaller
    
    - name: Verify imports
      run: |
        cd src
        python -c "from app import InsuranceApp; import tkinter; print('Imports successful')"
    
    - name: Check resource files
      run: |
        cd src
        ls -la app_logo.png app_icon.ico || echo "Resource files missing"
    
    - name: Build executable with PyInstaller
      run: |
        cd src
        xvfb-run --auto-servernum wine pyinstaller --noconfirm --onefile --windowed --icon=app_icon.ico --add-data="app_logo.png;." --name=InsuranceApp --noupx app.py
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: InsuranceApp
        path: src/dist/InsuranceApp.exe
        retention-days: 30
